In [5]:
import numpy as np

# numpy의 ndarray 클래스는 np.array()로 생성한다.

# 1차원 배열
vec = np.array([1, 2, 3, 4, 5])
print("1차원 배열(벡터): ")
print("-"*15)
print(vec)
# 2차원 배열
mat = np.array([[10, 20, 30], [60, 70, 80]])
print("2차원 배열(행렬): ")
print("-"*15)
print(mat)

# numpy에는 축과 크기라는 개념이 존재한다.
# ndim 속성으로 축을 반환하며, 차원을 의미한다.
# shape 속성으로 크기를 반환하며, 값의 수를 의미한다.

print("vec과 mat의 축(차원): ")
print(vec.ndim, mat.ndim)
print("vec과 mat의 크기(값의 수): ")
print(vec.shape, mat.shape)

1차원 배열(벡터): 
---------------
[1 2 3 4 5]
2차원 배열(행렬): 
---------------
[[10 20 30]
 [60 70 80]]
vec과 mat의 축(차원): 
1 2
vec과 mat의 크기(값의 수): 
(5,) (2, 3)


In [8]:
import numpy as np

# ndarray 클래스는 다양한 형태로 초기화(Initialize)가 가능

# np.zeros((축, 열))로 모든 값이 0인 ndarray
zero_mat = np.zeros((2, 3))
print("np.zeros((2, 3))")
print(zero_mat)

print("-"*15)
# np.ones((축, 열))로 모든 값이 1인 ndarray
one_mat = np.ones((2, 3))
print("np.ones((2, 3))")
print(one_mat)

print("-"*15)
# np.full((축, 열), 지정값)로 모든 값을 지정값인 ndarray
same_value_mat = np.full((2,3), 7)
print("np.full((2, 3), 7)")
print(same_value_mat)

np.zeros((2, 3))
[[0. 0. 0.]
 [0. 0. 0.]]
---------------
np.ones((2, 3))
[[1. 1. 1.]
 [1. 1. 1.]]
---------------
np.full((2, 3), 7)
[[7 7 7]
 [7 7 7]]


In [10]:
import numpy as np

# np.eye(행)로 대각선 값이 1이고 나머지가 0인 2차원 ndarray
# 또는 행렬의 단위행렬 I

eye_mat = np.eye(3)
print("np.eye(3)")
print(eye_mat)

print("-"*15)
# np.random.random((축, 열))로 임의의 값을 가지는 ndarray
random_mat = np.random.random((2, 3))
print("np.random.random((2, 3))")
print(random_mat)

np.eye(3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
np.random.random((2, 3))
[[0.56562299 0.85872463 0.45698615]
 [0.1932738  0.73458838 0.57390982]]


In [13]:
import numpy as np

# np.arange(값)로 0부터 값-1까지의 값을 가지는 nparray
# np.arange(시작, 끝, 단계)로 시작부터 끝-1까지 단계값 씩 증가

range_vec = np.arange(10)
print("np.arange(10)")
print(range_vec)
range_n_step_vec = np.arange(1, 10, 2)
print("np.arange(1, 10, 2)")
print(range_n_step_vec)

print("-"*15)

# np.reshape()는 내부 데이터는 변경하지 않고 배열의 구조를 바꿈

reshape_mat = np.array(np.arange(30)).reshape((5, 6))
print("np.array(np.arange(30)).reshape((5, 6))")
print(reshape_mat)

np.arange(10)
[0 1 2 3 4 5 6 7 8 9]
np.arange(1, 10, 2)
[1 3 5 7 9]
---------------
np.array(np.arange(30)).reshape((5, 6))
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [14]:
import numpy as np

# ndarray 클래스는 슬라이싱이 가능

mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)
print("첫번째 행:", mat[0, :])
print("두번째 열: ",mat[:, 1])

[[1 2 3]
 [4 5 6]]
첫번째 행: [1 2 3]
두번째 열:  [2 5]


In [22]:
import numpy as np

# numpy 연산

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("x:", x)
print("y:", y)
print("x+y =", x+y)
print("x-y =", x-y)
print("x*5 =", x*5)
print("y/2 =", y/2)

x: [1 2 3]
y: [4 5 6]
x+y = [5 7 9]
x-y = [-3 -3 -3]
x*5 = [ 5 10 15]
y/2 = [2.  2.5 3. ]
